### ISSUE TITLE
Use of tags as branch names

### ISSUE THREAD

**Issue by Roy-Orbison** [adminerevo/adminerevo#32]
Could you possibly use something like `releases` or `stable` as the branch name for the latest tag release? Otherwise the list of branches gets polluted with duplicates of tag names, and can cause confusion.

**Comment by Roy-Orbison** [comment]
Specifically, [this branch name](https://github.com/adminerevo/adminerevo/tree/v4.8.2) doesn't make much sense.

If you're planning on backporting fixes, a `v4.8.x` branch or `v4.x` branch would be logical.

**Comment by nodiscc** [comment]
@LionelLaffineur  Please at least delete the `v4.8.2` branch (but keep the tag), as it produces the following error/warning:

```
~/GIT/adminerevo (main =)$ git checkout v4.8.2 
warning: refname 'v4.8.2' is ambiguous.
Switched to branch 'v4.8.2'
Your branch is up to date with 'origin/v4.8.2'.
```

This causes git to checkout the branch named v4.8.2, with no obvious way to check out the tag with the same name.

**Comment by Roy-Orbison** [comment]
@nodiscc You can always disambiguate by using the `refs/` prefixes, e.g.:
```sh
git switch --detach refs/tags/v4.8.2
```
But the branch does still need to be removed.

**Comment by LionelLaffineur** [comment]
Done for this new 4.8.3.

**Comment by Roy-Orbison** [comment]
Still showing for me:
![tag-branch](https://github.com/adminerevo/adminerevo/assets/28617290/8eb12d15-44a1-43e7-bc0c-5b747c9070e7)

```sh
git push origin --delete v4.8.2
```
should assume you mean to delete the branch, when a tag has the same name.

**Comment by Letme** [comment]
`git push origin :v4.8.2` also works without fear of deleting tags because you pust the empty branch.

**Comment by Roy-Orbison** [comment]
@Letme the two operations are identical. Both delete a remote matching ref, and if it doesn't first match a branch, it will delete a tag.
