### ISSUE TITLE
Warning: Undefined property: Min_DB::$info in adminer.php on line 1595

### ISSUE THREAD

**Issue by francoisjacquet** [adminerevo/adminerevo#55]
Hello,

I would like to report a PHP warning when deleting rows, or performing a `DROP OWNED BY user` request.

Database type is PostgreSQL.

![image](https://github.com/adminerevo/adminerevo/assets/4723501/fd27e6a4-48e0-4ece-8ba9-c26d5a10b4a3)

**Comment by francoisjacquet** [comment]
Another one for PostgreSQL:

![image](https://github.com/adminerevo/adminerevo/assets/4723501/11c28a24-d0e3-49c2-80ce-6dcc1076798a)
PHP Warning: Undefined property: stdClass::$table in /var/www/html/adminer.php on line 1488

**Comment by LionelLaffineur** [comment]
Dear @francoisjacquet,
Thanks for reporting these issues. I've done some testing on my side and could not reproduce the symptom you describe.
May I suggest you to test it using the master branch where it is possible it is already fixed ?
And by using a not compiled version, if you report an error, I will be able to see it clearly in the code which is not so easy with the compiled version.
Regards,
L.

**Comment by francoisjacquet** [comment]
@LionelLaffineur I will update with the latest version when it is released, and will let you know. This is the best I can do right now.

**Comment by francoisjacquet** [comment]
Hello @LionelLaffineur 

I have done some tests with version 4.8.3

The warnings are still present, but not on the same line.

![image](https://github.com/adminerevo/adminerevo/assets/4723501/fc23ab09-0920-4e6b-a4a4-4380f63aeec2)

![image](https://github.com/adminerevo/adminerevo/assets/4723501/7b49eeaf-00eb-45ae-a74e-69e66f87e632)

**Comment by OmlineEditor** [comment]
I confirm that there is a similar problem with the database PostgreSQL.
Test version 4.8.3

Warning: Undefined property: Min_DB::$info in /home/user/www/adminer.php on line 1630
